### ISSUE TITLE
Issue with Ionic Framework

### ISSUE THREAD

**Issue by niconaso** [MrFrankel/ngx-popper#16]
The tooltip doesn't hide when input lost focus. This occurs only on the mobile, not in browser. Do you provide any method to hide the tooltip manually?
Perpahs this issue is related with this one: https://github.com/FezVrasta/popper.js/issues/340

**Comment by MrFrankel** [comment]
@niconaso 
probably not related to the popper issue since I only use popper.js to position the element, I handle the hide/show mechanism.

you can manage it manually like so:

<input popper="popperContent", popperTrigger="click" (blur)="popperContent.hide()"/>
<popper-content #popperContent>blab blab</popper-content>

**Comment by niconaso** [comment]
@MrFrankel thank you very much!
